### ISSUE TITLE
Como puedo Implementar su codigo de Facturación Electrónica?? Atento saludo, quiero implementar este codigo en mi sistema de facturación  http://chamansos.com/ecyberx Usuario: henry Clave: henry  Por favor escribeme al whatsapp +57 314 775 4208 que estoy un poco perdido

### ISSUE THREAD

**Issue by henrypandales** [odoocoop/facturacion_electronica#4]
Como puedo Implementar su codigo de Facturación Electrónica??
Atento saludo, quiero implementar este codigo en mi sistema de facturación 
http://chamansos.com/ecyberx
Usuario: henry
Clave: henry

Por favor escribeme al whatsapp +57 314 775 4208
que estoy un poco perdido

**Comment by dansanti** [comment]
hola, 
1.- recordar que esto es para chile, 
2.- esto es para odoo
3.- para api individualizada debe ver los ejemplo en gitlab.com/dansanti/facturacion_electronica

se cierra este issue ya que no es ussue es solicitud de soporte
